from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime

from app.models.signal import Signal


@dataclass(slots=True)
class Trade:
    """
    Represents a trade generated by a strategy.
    """

    symbol: str

    signal: Signal

    quantity: float

    entry_price: float

    stop_loss: float

    take_profit: float

    leverage: int = 1

    trading_mode: str = "PAPER"

    created_at: datetime = field(default_factory=datetime.utcnow)

    order_id: int | None = None

    status: str = "PENDING"

    def is_buy(self) -> bool:
        return self.signal is Signal.BUY

    def is_sell(self) -> bool:
        return self.signal is Signal.SELL

    def mark_simulated(self) -> None:
        self.status = "SIMULATED"

    def mark_filled(self, order_id: int) -> None:
        self.status = "FILLED"
        self.order_id = order_id

    def mark_rejected(self) -> None:
        self.status = "REJECTED"