from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime

from app.models.signal import Signal


@dataclass(slots=True)
class Trade:
    """
    Represents a trade generated by a strategy.
    """

    symbol: str

    signal: Signal

    quantity: float

    entry_price: float

    stop_loss: float

    take_profit: float

    leverage: int

    trading_mode: str

    created_at: datetime = field(default_factory=datetime.utcnow)

    order_id: int | None = None

    status: str = "PENDING"

    def is_buy(self) -> bool:
        """
        Returns True if this is a BUY trade.
        """
        return self.signal is Signal.BUY

    def is_sell(self) -> bool:
        """
        Returns True if this is a SELL trade.
        """
        return self.signal is Signal.SELL

    def mark_filled(self, order_id: int) -> None:
        """
        Mark the trade as filled.
        """
        self.order_id = order_id
        self.status = "FILLED"

    def mark_rejected(self) -> None:
        """
        Mark the trade as rejected.
        """
        self.status = "REJECTED"

    def mark_simulated(self) -> None:
        """
        Mark the trade as simulated.
        """
        self.status = "SIMULATED"